### ISSUE TITLE
X-Checksum header

### ISSUE THREAD

**Issue by jamesheck2019** [nubium/searchapi#24]
> ## X-Checksum
> Security checksum to sign your request with, assuring API that request was not tampered with.
<br>
explain more>>> md5 of what?

**Comment by SpareParts** [comment]
Hi James,
normally, we do not provide this information to general public. If you are interested in using our API I would advise you to contact our support through the contact form at our pages: https://ulozto.net/kontaktni-formular (EN) or https://uloz.to/kontaktni-formular (CZ).
